### ISSUE TITLE
error in travis integration?

### ISSUE THREAD

**Issue by lcerrato** [OpenGreekAndLatin/Latin#11]
@ThomasK81 
I tried to clone all of the settings from the 1st1k repo over here when I created Latin but this is throwing some sort of authentication error, I think, when it tries to build/release: (I can get the HookTests running ok)
https://travis-ci.org/github/OpenGreekAndLatin/Latin/builds/708441266

remote: No anonymous write access.
fatal: Authentication failed for 'https://@github.com/OpenGreekAndLatin/Latin/'
The command "git push -q https://$GITPERM@github.com/OpenGreekAndLatin/Latin --tags" failed and exited with 128 during .

I think I had to create tokens previously? I'm not sure what's missing. 

Maybe some zenodo integration could be done here as well.

**Comment by ThomasK81** [comment]
We just needed to set a GITPERM in Travis. I quickly generated one used it for the Latin Repo and also updated the GITPERM at First1KGreek

**Comment by ThomasK81** [comment]
In fact, I will update GitHub Actions and move away from Travis. That will make setting up new repos a lot easier.

**Comment by ThomasK81** [comment]
Github Action integration with 9e52b87
On push to Master the Action performs a Hooktest and creates an release if successful
