### ISSUE TITLE
show word count on hook test?

### ISSUE THREAD

**Issue by lcerrato** [OpenGreekAndLatin/Latin#17]
@ThomasK81 
I'm doing an inventory for the website. Is there somewhere I can see the word count breakdown for the repo? I use the hook test results to count repo words by language and passing texts.
Let me know if I'm missing something.
Thanks!

**Comment by lcerrato** [comment]
Also the First 1k release includes plain text versions which aren't included here.

**Comment by ThomasK81** [comment]
We could use TEItoCEX to produce plain text CSV and word counts. Should we do that?

**Comment by lcerrato** [comment]
added to code
